version: '2'
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    # When running in production environment, use expose instead of ports.
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "sranking"
    container_name: sranking-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    shm_size: '256mb'
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./screenshots:/var/tmp/screenshots
      - ./cache:/app/cache

volumes:
  pgdata:
    driver: "local"
